### ISSUE TITLE
Upload pics from one drive to instagram

### ISSUE THREAD

**Issue by pulbere** [torsden/streetartottawa.ca#10]
OneDrive pictures: 
https://1drv.ms/f/s!AtARX1jenNJChEm0FrzPzlo3amtW

select a few good ones, process them and upload to instagram
to process means: edit, crop, adjust

Instagram user:   streetartottawa

for PW ping me, I'll provide

**Comment by iulianturcanu** [comment]
Check out the added picks

**Comment by iulianturcanu** [comment]
corrected
