### ISSUE TITLE
Pick html template 

### ISSUE THREAD

**Issue by pulbere** [torsden/streetartottawa.ca#18]
from
https://www.styleshout.com/
https://html5up.net/
https://elements.envato.com/

5 hours max
post your choices as comments

**Comment by iulianturcanu** [comment]
Template variant 1 https://html5up.net/halcyonic
Variant 2 https://html5up.net/parallelism

**Comment by mipulbere** [comment]
https://www.styleshout.com/demo/?theme=abstract
https://www.styleshout.com/demo/?theme=puremedia

**Comment by mipulbere** [comment]
theme: http://jekyllthemes.org/themes/urban/
demo: https://narkotyk.net/
